// 海岸坐标场测试：离岸距离、坡度、泊港标记、涌浪到达延迟与耗时
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = dirname(dirname(fileURLToPath(import.meta.url)));
const code = ['01_util.js', '02_layout.js', '03_terrain.js', '03b_shore.js'].map(f => readFileSync(join(root, 'src', f), 'utf8')).join('\n');
const { buildTerrain, buildShoreField, G } = new Function(code + '\nreturn { buildTerrain, buildShoreField, G };')();
const X = buildTerrain(), t0 = Date.now(), S = buildShoreField(X.H, X.sdW), ms = Date.now() - t0;
let fail = 0; const ok = (c, m) => { console.log((c ? '通过 ' : '失败 ') + m); if (!c) fail++; };
const at = (x, z) => { const o = ((z - G.z0) * G.nx + (x - G.x0)) * 4; return { n: S.f0[o], gx: S.f0[o + 1], gz: S.f0[o + 2], slope: S.f0[o + 3], expo: S.f1[o], delay: S.f1[o + 1], lag: S.f1[o + 3], H: X.H[o / 4] }; };
ok(ms < 1500, `烘焙耗时 ${ms} 毫秒（后台线程，< 1500）`);
const b = at(0, 46); ok(b.lag === 1 && b.n > 3 && b.n < 20, `泊港沙滩前水面 n=${b.n.toFixed(1)} 米，泊港标记 ${b.lag}`);
ok(b.gz > 0.8, `沙滩前离岸方向朝南 gz=${b.gz.toFixed(2)}`);
ok(b.slope > 0.03 && b.slope < 0.15, `沙滩坡度 ${b.slope.toFixed(3)}（约 1:16）`);
const c = at(0, 215); ok(c.n > 5 && c.slope > 0.3, `南侧崖外 n=${c.n.toFixed(1)}，坡度 ${c.slope.toFixed(2)}（陡崖）`);
const nS = at(0, 218), nN = at(0, -212);
console.log(`到达延迟：南崖 ${nS.delay.toFixed(1)} 秒，北崖 ${nN.delay.toFixed(1)} 秒，泊港沙滩 ${b.delay.toFixed(1)} 秒；最大 ${S.delayMax.toFixed(1)} 秒`);
ok(nN.delay > nS.delay + 10, '北侧（背浪面）晚于南侧');
ok(nN.expo < 0.5 && nS.expo > 0.8, `迎浪程度 南 ${nS.expo.toFixed(2)} 北 ${nN.expo.toFixed(2)}`);
let bad = 0; for (const v of [S.f0, S.f1, S.f2]) for (let i = 0; i < v.length; i++) if (!Number.isFinite(v[i])) bad++;
ok(bad === 0, `无 NaN / Inf（${bad}）`);
if (fail) { console.log(`\n${fail} 项失败`); process.exit(1); } else console.log('\n海岸坐标场全部通过');
